version: 2
enable-beta-ecosystems: true

updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"

    - package-ecosystem: "nuget"
      directory: "/Wok"
      schedule:
          interval: "daily"
      versioning-strategy: increase
